# Define a git hook

define git::defhook::def {
    include concat::setup

    $hook = $title

    concat {$hook:
        mode => 0755,
    }

    concat::fragment {"$hook header":
        target => "$hook",
        content => "#!/bin/bash\n# Autogenerated by Puppet, do not modify",
        order => 01,
    }

}
